#!/usr/bin/php
<?php

	require_once(dirname(dirname(__FILE__)) . '/absolute-url-deriver/src/webignition/AbsoluteUrlDeriver/AbsoluteUrlDeriver.php');
	require_once(dirname(dirname(__FILE__)) . '/php-ogp/ogp/Parser.php');
	require_once(dirname(dirname(__FILE__)) . '/php-mf2/Mf2/Parser.php');

	function getUrl($url) {
		global $version;
		
		$curl_handle=curl_init();
		curl_setopt($curl_handle,CURLOPT_URL,$url);
		curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,5);
		curl_setopt($curl_handle, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curl_handle, CURLOPT_USERAGENT, "pingback2hook $version");

		$buffer = curl_exec($curl_handle);
		$http_status = curl_getinfo($curl_handle, CURLINFO_HTTP_CODE);
		
		curl_close($curl_handle);
		
		return array('content' => $buffer, 'status' => $http_status);
	}


	echo "Metainspecting {$argv[1]}... ";
	$content = getUrl($argv[1]);
	
	echo "status: {$content['status']}\n\n";
	
	echo "Open Graph\n";
	echo "----------\n";
	print_r(\ogp\Parser::parse($content['content']), true);
	
	
	echo "\nMF2\n";
	echo "---\n";

			if ($parser = new \mf2\Parser($content['content'])) {
				print_r( $parser->parse());
			}
			else
			{
echo	"Errrp! No microformats found... if this site is yours, you might want to add some Indieweb Microformats in order to help others parse your content! Check out http://microformats.org/wiki/microformats2\n";
			}
		
		
